version: 0.0.{build}-pre
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:  
    secure: 4guKYW7T2AsE96Wgu0J9RFtVYKSYRxU3L/pzz8UxJpv6uXXSfizwTF4s7iKUDk32
  RocketServer:
    secure: Sbzwrt3Y8bKWeuykWXHeBIzqd16ajEcJBiDOdDyo2+E=
before_build:
- ps: nuget restore
build:
  project: Rocket.Chat.Net.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test_script:
#- ps: packages\xunit.runner.console.2.1.0\tools\xunit.console "test\Rocket.Chat.Net.Tests\bin\Debug\Rocket.Chat.Net.Tests.dll" -verbose -notrait category=Sandbox -parallel none
- ps: .\test.ps1
deploy: off
